# Para sites estáticos simples (HTML/CSS/JS apenas)
steps:
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['-m', 'rsync', '-r', '-c', '-d', './', 'gs://aucto/']

options:
  logging: CLOUD_LOGGING_ONLY

# Para projetos com build (React, Vue, etc.), use isto:
# steps:
#   - name: 'node:18'
#     entrypoint: 'npm'
#     args: ['ci']
#   
#   - name: 'node:18'
#     entrypoint: 'npm'
#     args: ['run', 'build']
#   
#   - name: 'gcr.io/cloud-builders/gsutil'
#     args: ['-m', 'rsync', '-r', '-c', '-d', './build/', 'gs://aucto/']
# 
# options:
#   logging: CLOUD_LOGGING_ONLY

timeout: '1200s'
